### ISSUE TITLE
How to import this project to my website?

### ISSUE THREAD

**Issue by mvelisomakhenkce** [MarcoCiaramella/cpu-web-miner#12]
This is a very interesting project but it has no documentation. Let's say I do have a website and I want to embed this project so that mining gets executed when the said website is being visited.Where are the steps that I should follow when making use of this project?

Detailed instructions would be highly appreciated. At least a Youtube video would do justice.

There's a similar project found at https://webminer.pages.dev/

The guy even did a detailed video that can be found at: https://www.youtube.com/watch?v=czpmk7ZugWQ

I just need instructions bro, please help :(

**Comment by MarcoCiaramella** [comment]
Hello @mvelisomakhenkce 
it's a classic npm frontend module and it's out of this repo to explain how to use npm libraries in your project. On Google or chatgpt you can find the answer

**Comment by MarcoCiaramella** [comment]
I close this. please refer to my reply in your second issue 🙏
