### ISSUE TITLE
Algo addition request

### ISSUE THREAD

**Issue by williamarmenta54** [MarcoCiaramella/cpu-web-miner#14]
I really appreciate your work bro, especially the addition of Ghostrider algo, that really illustrates that this project is growing and more relevant than anyone could think.

Yespower algo is already supported, and I would really appreciate if you could add support for Power2b, which is a slight modification of Yespower by replacing sha256 with blake2b.

For more info, sources-:
https://github.com/MicroBitcoinOrg/MicroBitcoin
https://github.com/MicroBitcoinOrg/Power2B

**Comment by MarcoCiaramella** [comment]
hello @williamarmenta54  thanks for your support and your request.
Yes I can add Power2b, no problem

**Comment by williamarmenta54** [comment]
That would be very wonderful Sir. I will kindly wait for for your next release with Power2b support added :)

**Comment by MarcoCiaramella** [comment]
hello @williamarmenta54  I've just released v1.5.0 with power2B. Thanks for your request!
