### ISSUE TITLE
Algo ghostrider tested

### ISSUE THREAD

**Issue by vpts1202** [MarcoCiaramella/cpu-web-miner#15]
Hello @MarcoCiaramella 

I have just tested your html file as is( RTM address was replaced to mine only).
Its looks like that script itself is workable. At least CPU usage is high and come up to 100%

However there is no signs of live at pool dashboard.
So the issue is either at your intermediary server or at the pool end.

For your reference below is errors, warnings,etc, I have got during the test 
Type	Message text
log	num threads: 2
log	new work: JSHandle@object
error	failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0x
error	Aborted(CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0xfd (enable with --experimental-
error	failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0x
error	Aborted(CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0xfd (enable with --experimental-
error	RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0xfd (enable with -
error	RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0xfd (enable with -

Please advise.
Thanks

**Comment by MarcoCiaramella** [comment]
hello @vpts1202  seems the wasm code, the miner itself or part of it, cannot run on your browser.
The error could be releated to SIMD instructions. Can you write on which browser and os you tested your code?

**Comment by vpts1202** [comment]
Well, OS Windows desktop and browsers are all major firefox,chrome, edge

Please try to fix. If your product will be stable I will redirect all my traffic in full scale.
Also please advise what should be changed in your html code in case if  I will want to mine coin other than raptoreum but with the same ghostrider algo, e.g. GeckoCoin(GEC) 
Thanks

**Comment by MarcoCiaramella** [comment]
@vpts1202 ok thanks. Have you tried another algo? From the websocket server I see that minotaurx and power2b work fine. I suggest you try with one of these

**Comment by M-Kleinschmidt** [comment]
Hello everyone,

I tested it and everything seems to work for me, see screenshot. I checked it under Chrome on a Windows 10 computer. Hope it helps with troubleshooting. 

![image](https://github.com/user-attachments/assets/abe8982b-3e58-42c0-815e-f9d37a90d657)

**Comment by MarcoCiaramella** [comment]
> Hello everyone,
> 
> I tested it and everything seems to work for me, see screenshot. I checked it under Chrome on a Windows 10 computer. Hope it helps with troubleshooting.
> 
> ![image](https://private-user-images.githubusercontent.com/81569589/373415039-abe8982b-3e58-42c0-815e-f9d37a90d657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTM0NzMsIm5iZiI6MTcyNzk5MzE3MywicGF0aCI6Ii84MTU2OTU4OS8zNzM0MTUwMzktYWJlODk4MmItM2U1OC00MmMwLTgxNWUtZjlkMzdhOTBkNjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDIyMDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNWQ4ODIwNGFjMmNhYjhmOGZmYzRlYTVhYmVlYzdkZTA0NWY2ZTU1ZGUyMTBjYzQ5M2EzZThjOTQwOWY5OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5NL-22mOr8RTHTWGosav1byGJrOJrKTolaxGN-O_tTY)

thank you!

**Comment by MarcoCiaramella** [comment]
@vpts1202 is this your pool config?

```
    server: '49.13.201.148',
    port: 4444,
    worker: 'test',
    password: 'x',
    ssl: false,
```

**Comment by vpts1202** [comment]
> @vpts1202 is this your pool config?
> 
> ```
>     server: '49.13.201.148',
>     port: 4444,
>     worker: 'test',
>     password: 'x',
>     ssl: false,
> ```

Nope. Thats not mine
I have used config that is deployed in Read Me section of your repo,i.e.:

<!DOCTYPE html>
<html>
<body>

<h2>Thanks for using cpu-web-miner</h2>

<script type="module">
import * as cpuWebMiner from 'https://esm.run/@marco_ciaramella/cpu-web-miner';

const stratum = {
    server: "europe.raptoreum.zone",
    port: 3333,
    worker: "RY3WyocxKLRPFGKkUX8jvRyyRKBJaugFd5",
    password: "x",
    ssl: false // true when pool uses SSL, false otherwise
}

cpuWebMiner.start(cpuWebMiner.ghostrider, stratum, true, cpuWebMiner.ALL_THREADS);
</script> 

</body>
</html>

The only change I made is replaced your RTM address to mine.

**Comment by MarcoCiaramella** [comment]
> > @vpts1202 is this your pool config?
> > ```
> >     server: '49.13.201.148',
> >     port: 4444,
> >     worker: 'test',
> >     password: 'x',
> >     ssl: false,
> > ```
> 
> Nope. Thats not mine I have used config that is deployed in ReadMe(->Usage) section of your repo The only change I made is replaced your RTM address to mine.

ok please paste here your code used. thanks

**Comment by vpts1202** [comment]
> > > @vpts1202 is this your pool config?
> > > ```
> > >     server: '49.13.201.148',
> > >     port: 4444,
> > >     worker: 'test',
> > >     password: 'x',
> > >     ssl: false,
> > > ```
> > 
> > 
> > Nope. Thats not mine I have used config that is deployed in ReadMe(->Usage) section of your repo The only change I made is replaced your RTM address to mine.
> 
> ok please paste here your code used. thanks

OK.
<script type="module">
import * as cpuWebMiner from 'https://esm.run/@marco_ciaramella/cpu-web-miner';

const stratum = {
    server: "europe.raptoreum.zone",
    port: 3333,
    worker: "MY-RTM Wallet-Address",
    password: "",
    ssl: false // true when pool uses SSL, false otherwise
}

cpuWebMiner.start(cpuWebMiner.ghostrider, stratum, true, cpuWebMiner.ALL_THREADS);
</script>

**Comment by MarcoCiaramella** [comment]
@vpts1202 your code works on my machine but from your log above I see this line

>num threads: 2

this means your CPU have two cores so I suppose it is an old CPU, 12/15 years old or a low-budget one, and it doesn't support some SIMD instructions set.

This library is not intended for running on all possibile machine because it requires all recent SIMD instructions and on some browser it cannot run but the code you are using is right and you can add it to your website. Don't worry, visitors of your site with a more recent machine will be able to mine

**Comment by vpts1202** [comment]
Hello @MarcoCiaramella. Thank you for your feedback.
In fact,for this test I have used three different app/performance test service platforms in dozen machines. The logs I have sent were random from one out of three.
What I have heard is that the issue is in ghostrider pools Blob templates startum structure.
However all opinions including yours are open and possible.

**Comment by MarcoCiaramella** [comment]
hello @vpts1202 . I reopen this issue because it could be releated to high memory usage.
During my analisys I noticed an abnormal ram consumption with the last version.
The error
>  failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0x

could affect machines with low ram. I'm investigating on it.

**Comment by MarcoCiaramella** [comment]
@vpts1202 I've just released v1.5.1 with ram issue fixed. Could you verify your issue again?

**Comment by vpts1202** [comment]
> @vpts1202 I've just released v1.5.1 with ram issue fixed. Could you verify your issue again?

Hey @MarcoCiaramella ,will test it and let you know then. Thank you!
Should I use the same HTML code that you have provided in ReadMe section of this repo,no changes?

**Comment by MarcoCiaramella** [comment]
> > @vpts1202 I've just released v1.5.1 with ram issue fixed. Could you verify your issue again?
> 
> Hey @MarcoCiaramella ,will test it and let you know then. Thank you! Should I use the same HTML code that you have provided in ReadMe section of this repo,no changes?

yes the same code. Thank you!

**Comment by vpts1202** [comment]
> > > @vpts1202 I've just released v1.5.1 with ram issue fixed. Could you verify your issue again?
> > 
> > 
> > Hey @MarcoCiaramella ,will test it and let you know then. Thank you! Should I use the same HTML code that you have provided in ReadMe section of this repo,no changes?
> 
> yes the same code. Thank you!

Its just not workable, mate.
129 devices were in test, by 60sec time visit each. 
Errors, warnings etc
Type	Message text
log	num threads: 2
log	new work: JSHandle@object
error	failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0x
error	Aborted(CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0xfd (enable with --experimental-
error	RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0xfd (enable with -
error	failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0x
error	Aborted(CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0xfd (enable with --experimental-
error	RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #13 failed: Invalid opcode 0xfd (enable with -

**Comment by MarcoCiaramella** [comment]
@vpts1202  can I have the webiste link where miner is installed? thank you

**Comment by vpts1202** [comment]
> @vpts1202 can I have the website link where miner is installed? thank you

There is nothing to do with my website. The issue either at your script/server/etc., or at the pool which not let mining job/connection.
Thanks

**Comment by MarcoCiaramella** [comment]
> > > > @vpts1202 is this your pool config?
> > > > ```
> > > >     server: '49.13.201.148',
> > > >     port: 4444,
> > > >     worker: 'test',
> > > >     password: 'x',
> > > >     ssl: false,
> > > > ```
> > > 
> > > 
> > > Nope. Thats not mine I have used config that is deployed in ReadMe(->Usage) section of your repo The only change I made is replaced your RTM address to mine.
> > 
> > 
> > ok please paste here your code used. thanks
> 
> OK.
> 
> ```
> <script type="module">
> import * as cpuWebMiner from 'https://esm.run/@marco_ciaramella/cpu-web-miner';
> 
> const stratum = {
>     server: "europe.raptoreum.zone",
>     port: 3333,
>     worker: "MY-RTM Wallet-Address",
>     password: "",
>     ssl: false // true when pool uses SSL, false otherwise
> }
> 
> cpuWebMiner.start(cpuWebMiner.ghostrider, stratum, true, cpuWebMiner.ALL_THREADS);
> </script> 
> ```

@vpts1202 are you still using this code?

**Comment by vpts1202** [comment]
@MarcoCiaramella Well, I wish to:).Have you found what is the problem is?

**Comment by MarcoCiaramella** [comment]
@vpts1202 no sorry but I have just created a discord server for technical support. Please click on the widget in the readme page.

I'll close this issue with the solution when we found it :)

**Comment by vpts1202** [comment]
Hello @MarcoCiaramella 
I think I have found where the issue is.
Very roughly it looks as follows: While connecting to your server, first hashing is going to dev fees, afterward to my wallet. If connection duration(the time spent on page) is lengthy, after certain time interval this cycle is repeated, i.e. initially hashing to dev fee wallet and then to my wallet.

For the testing purposes I have used 60sec.duration of connection(the time spent on page), however normally I am using high frequency, multiplying traffic. The connections duration(the time spent on page) are varies from 0,1sec to 2,5sec.,each. So connections were simply terminated before any hashes could start to flow into my wallet. Therefore CPU usage, memory, looks fine but no signs of activity on my dashboard pool.
There are solutions, but all depend from you, e.g. reducing time interval to msecs, or to use techniques of multi-coins pools or famous in past web miners like Coinhive or Crypo-Loot.etc.
Thanks

**Comment by vpts1202** [comment]
Hello good man @MarcoCiaramella 
I have missed out such crucial factor as pool entry difficulty limits. Its make sense(and I will) to continue testing/experimenting, just with more selective approach to the coin network hashrate and pool entrance requirement.
With regard of it:
1) Can you please confirm that website integrating code for RTM coin(ghostrider algo) that you have deployed in ReadMe section is still valid and useful if I will replace pool/port?
2) Can you please provide website integrating code for Fsociety(FSC) coin(ghostrider algo)?
3)  Can you please provide website integrating code for MicroBitcoin(MBC) coin(power2b algo)?
Thank you!
PS: Please don’t drop support of this project:) You have not much competitors at all, but demand from webmasters specialising on traffic, is really huge, So with right approach you will become the leader in this niche very quick.

**Comment by MarcoCiaramella** [comment]
hello @vpts1202 
thanks for supporting this project!

About your questions you have only to specify pool config in the stratum param in the start() function and pass the right algo constant as in the example. have you see errors with RTM, FSC and MBC?

**Comment by vpts1202** [comment]
I have not tested yet(have been waiting for your feedback), will let you know. I am pretty sure the issue was in the pool initial difficulty

**Comment by MarcoCiaramella** [comment]
ok. you can join the discord server for a real-time help

**Comment by vpts1202** [comment]
Hello @MarcoCiaramella 

I have noticed that script for website background mining at readme section of this repo is differ from the same at you page :npmjs.com/package/@marco_ciaramella/cpu-web-miner
Please advise
Thanks

**Comment by MarcoCiaramella** [comment]
hello @vpts1202 thanks for reporting! I deployed the dev branch instead of main. I've already fixed it.
thanks again!

**Comment by vpts1202** [comment]
Hello @MarcoCiaramella 
I have completed tests of your ghostrider algo script. All works fine!
Hashes “production” is lower in compare to your closest competitor:) But that's not the issue. Commercially everyone has the right to determine own price and margin. Certainly I will start to use you webminer. Well done. Thank you!

**Comment by MarcoCiaramella** [comment]
hello @vpts1202 can you do a test with ghostrider? I had fix a critical bug that blocks mining after some shares
