### ISSUE TITLE
Custom options from the client side

### ISSUE THREAD

**Issue by williamarmenta54** [MarcoCiaramella/cpu-web-miner#17]
It's good to see that this project is adding more features and growing. However the project is very restrictive from the client/or the visitor of the site that is being monetized.

Sometimes a visitor knows enough to set up their own VPS and deploy your web miner but has CPU's with different specifications or Cores. So it becomes very crucial that your web miner does not exhaust all the CPU cores when the website is being visited, therefore it would be very useful that the visitor be able to set the number of CPU cores used even though they don't have have root access to the VPS where the miner is installed.

A person visiting the website should be able to set number of threads used by the miner for his different CPU's/Computers, It should not only be up to the VPS owner who can only set high CPU cores even for visitors with low spec CPU's/Computers.

Sometimes someone own a  great number of spare computers but does not want to use Xmrig or SRBMiner, he/she only wants to use your nodejs app. One configuration that uses all of CPU cores/threads from the server will not be feasible for all of his/her CPU's, thereby satisfying the need for you to implement a way that a website visitor be able to set variables according to his needs without having to change values on the VPS where the nodejs app is installed.

When your CPU web Miner is installed, should not only hardcode one algorithm per VPS, consider a way where all supported algorithms are installed/enabled by default, maybe if the website visitor did not set any custom values (such as algo, pool, no. of cores), then randomly mine an algo that points to the hardcoded website owner's wallet . 

A good example is this website: https://webminer.pages.dev

A user sets a pool, algo number of cores, etc, but uses the owner's server where the code runs.

If I go to https://webminer.pages.dev?algorithm=minotaurx&host=fastpool.xyz&port=6000&worker=solo%3AMBqp1j1SARjzcy5ukYdAuriCaFX2hDpNgK%40%24Test&password=x&workers=4

The code will solo mine Maza coin at fastpool using 4 cores/threads without having to install anything, and without owning any VPS.

The use has control to set custom values, can you tweak your app so the user/visitor can set custom values too?

**Comment by MarcoCiaramella** [comment]
hello @williamarmenta54 not sure I got your question.

First of all [https://webminer.pages.dev/](url) is a web miner that uses my lib cpu-web-miner but the owner lost their project and is not updated.

About your question, I don't get why you talk about nodejs app. All the algos and logics are in this js module. This js module is **a WHOLE miner which runs algo in wasm.**
When you call `start()` function in your website code this [base64 string](https://github.com/MarcoCiaramella/cpu-web-miner/blob/40864f01ab857d3e41b2123f7c9596830843609f/index.js#L88) is ran on a [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers). You can set the number of Web Workers (threads) by passing a value for n. thread parameter.

There is no hardcoded algo and if you want to leave a user set parameters you have to implement an interface for it.

The main purposes of this js library are two. Monetize website, in this case the web developer installs the miner on his website and uses his own stratum config, or provide a web miner to users. In this case you explicitly create a page with an inteface where user adds his own stratum config like the website you mentioned.

**Comment by williamarmenta54** [comment]
![CWM](https://github.com/user-attachments/assets/d45ca0ea-61f2-4959-82cc-a0ff096dae6b)

**Comment by williamarmenta54** [comment]
My question was directed towards the second purpose you mentioned, where the dev provides a webminer to users by creating an interface where the user provides his stratum config like the website I provided earlier.

It would be wonderful you could implement a way where users could be able to pass mining variables within the URL of the website where the webminer is installed, just like the website I showed, or add a way where mining parameters such as worker name can be provided via a json config.

For example I do have my own website/VPS where I deployed this web miner, and my sole purpose is not to monetize but to use it for testing and for mining. The problem comes when I try to see individual miner's hash rate. If I mine with 5 CPU rigs, the hash rate is mingled, and the workers are seen as one from the pool.

It would be very wonderful if you could implement a way where it could be possible to set different parameters for different workers from the perspective of individual usage rather than monetization alone.

It is very useful to see each miner's performance by a custom worker name.

I customized this guy's script I saw here https://www.youtube.com/watch?v=czpmk7ZugWQ
So that it fits my needs

num_of_cores=`cat /proc/cpuinfo | grep processor | wc -l`
currentdate=$(date '+%d-%b-%Y_3900xFattyBoy_')
ipaddress=$(curl -s api.ipify.org)
underscored_ip=$(echo $ipaddress | sed 's/\./_/g')
currentdate+=$underscored_ip
used_num_of_cores=`expr $num_of_cores - 4`

cat > config.json <<END
{
  "algorithm": "minotaurx",
  "host": "flyingsaucer-eu.teatspray.fun",
  "port": 7019,
  "worker": "MGaypRJi43LcQxxxxxxxxxxxxxxxxxxxx",
  "password": "$currentdate,c=MAZA,zap=MAZA",
  "workers": $used_num_of_cores,
  "fee": "1"
}
END

sleep 5

echo "Your worker name is $currentdate"
sleep 2
pm2 start index.js --watch

My config for a worker name on your CPU Web Miner is by adding MiningAddress.CPUWebMinerTest. My screenshot will show. But that worker name is not unique it shows as a single mingled worker for all CPU Mining Rigs.




![CWM](https://github.com/user-attachments/assets/4fabe231-dd8f-46cd-a868-9c2c44494e5a)

**Comment by MarcoCiaramella** [comment]
> My config for a worker name on your CPU Web Miner is by adding MiningAddress.CPUWebMinerTest. My screenshot will show. But that worker name is not unique it shows as a single mingled worker for all CPU Mining Rigs.

`worker` parameter is used by stratum protocol to identify the worker in the stratum pool. MiningAddress.CPUWebMinerTest is right. When you open your web page on computer A you will pass MiningAddress.CPUWebMinerTest1, when you open on computer B you will pass MiningAddress.CPUWebMinerTest2 etc. On the stratum pool you'll see hashrate for CPUWebMinerTest1 and  CPUWebMinerTest2 is this right?

> It would be very wonderful if you could implement a way where it could be possible to set different parameters for different workers from the perspective of individual usage rather than monetization alone.
> 
> It is very useful to see each miner's performance by a custom worker name.

What you need is a web page that read parameter like `worker` from URL with an URL parser. Or add an intercefe where you write parameters.

cpu-web-miner has all default paramenters required by a crypto miner like a native miner and `worker` identifies your rig or computer in the stratum pool.

**Comment by williamarmenta54** [comment]
I opted to doing it myself: I edited maikn.js to

import * as cpuWebMiner from "@marco_ciaramella/cpu-web-miner";

const randomNumber = Math.floor(100000 + Math.random() * 900000);
const randomNumber2 = Math.floor(100000 + Math.random() * 900000);
const os = require('os');
const cpuCount = os.cpus().length;
const used_num_of_cores = cpuCount - 2;

const stratum = {
    server: "flyingsaucer-eu.teatspray.fun",
    port: 7019,
    worker: `MGaypRJi43Lcxxxxxxxxxxxxx.${randomNumber}`,
    password: "c=MAZA,zap=MAZA,m=solo,"+randomNumber2,
    ssl: false // true when pool uses SSL, false otherwise
}

cpuWebMiner.start(cpuWebMiner.minotaurx, stratum, true, cpuWebMiner.used_num_of_cores);

**Comment by MarcoCiaramella** [comment]
yes this could be a solution. Even though your example should be a monetization scenario and not webminer where user puts his own worker name.
Anyway if you want to give an ID to each worker automatically your solution is good, or you can use IP addr or timestamp as worker ID.
