### ISSUE TITLE
Coins supported

### ISSUE THREAD

**Issue by vpts1202** [MarcoCiaramella/cpu-web-miner#2]
Hello

Which particular coins of algos in your repo mentioned(yespower, yespowerR16, yescrypt,etc.) are supported?
Thanks.

**Comment by MarcoCiaramella** [comment]
hello @vpts1202 it supports all coins using the selected algo. You can find a list of coins on mining pools like [zpool ](https://zpool.ca/) or [rplant](https://pool.rplant.xyz/)

**Comment by MarcoCiaramella** [comment]
@vpts1202 note that Minotaurx is not available at the moment due to an implementation error. Also an optimization is on going #1
