### ISSUE TITLE
[New Algo] Can we support mining Dero (AstroBWT/v3) On Webminer

### ISSUE THREAD

**Issue by tuananh19961** [MarcoCiaramella/cpu-web-miner#3]
@MarcoCiaramella Can we support mining Dero (AstroBWT/v3) for this package

**Pool**: https://miningpoolstats.stream/dero
**Coin**: https://dero.io/
**Miner**: https://github.com/whalesburg/dero-stratum-miner

**Comment by MarcoCiaramella** [comment]
Hello @tuananh19961  sorry for the late reply.

I didn't find a C version of the algo so I have to port the GO source to C. I hope to deal with it asap :)

**Comment by tuananh19961** [comment]
Thank for your hardworking @MarcoCiaramella.
Wait good news from you.
