### ISSUE TITLE
Can mining multi threads algo minotaurx ?

### ISSUE THREAD

**Issue by Cook5567** [MarcoCiaramella/cpu-web-miner#6]
Hi I have a question, according to a friend of mine, algo minotaurx is having an error and cannot be used, so when can I use it?

**Comment by MarcoCiaramella** [comment]
hi,  yes I'm going to fix it next month

**Comment by Cook5567** [comment]
> hi, yes I'm going to fix it next month

So long

**Comment by MarcoCiaramella** [comment]
@Cook5567 sorry for the delay I was busy this days. Anyway I'll do my best to fix it next week

**Comment by Cook5567** [comment]
Is the fix done yet?

**Comment by MarcoCiaramella** [comment]
@Cook5567  just released 1.1.6 with the minotarux fix
