### ISSUE TITLE
RandomX algo

### ISSUE THREAD

**Issue by vpts1202** [MarcoCiaramella/cpu-web-miner#9]
Hello @MarcoCiaramella 

The main issue for both algos(yespower and minotaurx) is liquidity absence. Today for example the highest 24H volume among  yespower coins is $2,4K(SWAMP coin) and $527(MAZA) in minotaurx

Why don’t you focus on webminer for RandomX algo? There are real money and there are huge webmasters interest and demand.
Thanks

**Comment by MarcoCiaramella** [comment]
hello @vpts1202  thanks for your interest. I'm not sure it is 100% portable to wasm. The main problem is the performance. Current version of wasm doesn't support hardware AES resulting in a 100x slower execution or more. Another problem is about multi-threading used in VM execution. wasm doesn't support threading and I'm not sure web worker can do the work.
